In [2]:
import pandas as pd
import numpy as np

In [3]:
a = np.arange(15) #create simple array

In [12]:
a = a.reshape(3,5) #reshape array

In [7]:
a.itemsize

8

In [8]:
a.dtype.name #data type

'int64'

In [9]:
a.size #how many elements

15

In [13]:
a.ndim #number of dimensions

2

# Array Creation

In [15]:
b = np.array([0.1,0.2,0.3])

In [17]:
b.dtype

dtype('float64')

In [18]:
# np will convert interables to arrays
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [19]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
#specifying dtypes
c = np.array([1, 2.2, 3.3], dtype=complex)

In [21]:
c

array([1. +0.j, 2.2+0.j, 3.3+0.j])

In [32]:
# creating array of zeroes and ones
d = np.zeros((2,5), dtype=np.int16)
print(d)

d = np.ones((3,3,3), dtype=np.int16)
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [35]:
#empty creates a random array with default of float64
e = np.empty((2,3))
print(e)
e = np.empty((2,3), dtype=np.int16)
print(e)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[    0     0     0]
 [12288 22610 28092]]


In [37]:
#Arange uses start, stop, step or if one argument integers up to that point
np.arange(5, 25, 5)

array([ 5, 10, 15, 20])

In [41]:
#linspace uses start_of_space, end_of_space, numbers_within_the_space
np.linspace(0,10,6) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [42]:
from numpy import pi

In [44]:
x = np.linspace(0, 2*pi, 5)
y = np.sin(x)
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [45]:
#If the array is too large it will only pring corners

In [46]:
import sys

In [48]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [49]:
#this will fix that 
#np.set_printoptions(threshold=sys.maxsize)

# Basic Operations

In [66]:
f = np.arange(4, dtype=np.float16).reshape((2,2))
g = np.array([[0.1,0.2],[0.3,0.4]])
print(f)
print(g)
f - g

[[0. 1.]
 [2. 3.]]
[[0.1 0.2]
 [0.3 0.4]]


array([[-0.1,  0.8],
       [ 1.7,  2.6]])

In [67]:
f * g #elementwise multiplication

array([[0. , 0.2],
       [0.6, 1.2]])

In [68]:
f @ g #dot product multiplication

array([[0.3, 0.4],
       [1.1, 1.6]])

In [69]:
f += g #cannot cast int to float

In [70]:
f

array([[0.1, 1.2],
       [2.3, 3.4]], dtype=float16)

In [71]:
f > 2 #supports basic comparisons

array([[False, False],
       [ True,  True]])

In [72]:
f ** 2

array([[9.995e-03, 1.440e+00],
       [5.293e+00, 1.156e+01]], dtype=float16)

# Random Numbers

In [73]:
rg = np.random.default_rng(1) #random floating point number between 0 and 1 

In [75]:
rand = rg.random((2,3))
rand

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [76]:
rand.sum()

3.1057109529998157

In [77]:
rand.min()

0.027559113243068367

In [78]:
rand.max()

0.8277025938204418

# functions accros rows and columns

In [81]:
twelve = np.arange(12).reshape(3,4)
twelve

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
print(twelve.sum(axis=0))
print(twelve.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [86]:
print(twelve.cumsum(1))

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [87]:
twelve.min(axis=1)

array([0, 4, 8])

In [ ]:
# universal functions